version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-pkg-cache
      - run: make ci
      - save_cache:
          key: v1-pkg-cache
          paths:
          - ~/.cache/go-build

workflows:
  version: 2
  build-and-deploy:
    jobs:
    - build
